### ISSUE TITLE
The play button disappear on the smaller screen

### ISSUE THREAD

**Issue by trungvose** [nartc/super-expressive-playground#1]
Small screen

![image](https://user-images.githubusercontent.com/6767322/88879122-0fac5d80-d25c-11ea-8a84-4561ce6b6dae.png)

Expected

![image](https://user-images.githubusercontent.com/6767322/88879194-44b8b000-d25c-11ea-80a7-faa8046633a2.png)

**Comment by nartc** [comment]
Fixed by removing the button completely. Instead, keyboard events were adjusted:
- Windows: Ctrl + Enter should work
- MacOSX: both Ctrl + Enter or Cmd + Enter should work
- Editor: an action named Execute is now added to the Editor's context menu (right click)
